menus_printemps = ["Piémontaise",
                    "Salade César",
                    "Salade De Chèvre Chaud",
                    "Steaks / Poêlée Légumes",
                    "Palette A La Diable / Purée",
                    "Cordons Bleus / Pates / Salade",
                    "Escalope Panée/ Haricots Verts",
                    "Coquillettes Au Jambon",
                    "Steak Hache Œuf Plat / Galette De Pommes De Terre",
                    "Panes Tomates / Riz",
                    "Saumon Beurre / Riz",
                    "Aiguillettes Poulet / Légumes Asiatiques",
                    "Hamburgers / Frites",
                    "Paupiettes / Poêlée Parisienne",
                    "Pilon Poulet / Petits Pois Carottes",
                    "Knacks / Pâtes Fraiches", 
                    "Steaks Poivre / Kiddy Smile", 
                    "Tagliatelles Saumon", 
                    "Pizza", 
                    "Poulet / Frites", 
                    "Steaks Haches / Purée", 
                    "Omelette Ciboulette / Patates Rissolées", 
                    "Hachis Parmentier", 
                    "Quiche Lorraine / Salade", 
                    "Penne/Poulet/Tomates Séchées / Mozza", 
                    "Lasagnes / Salade", 
                    "Couscous",
                    "Escalopes / Ratatouille", 
                    "Spaghettis Boulettes Sauce Napo", 
                    "Crêpes Jambon Fromage / Pates", 
                    "Roti De Porc / Carottes Vichy", 
                    "Croques Monsieur / Salade Boursin", 
                    "Steak Hache / Purée",
                    "Gratin Coquillettes / Jambon",
                    "Risotto / Jambon Sec",
                    "Cuisses Poulet / Petits Pois Carottes",
                    "Cotes Porcs / Haricots Verts", 
                    "Saute De Porc A La Tomate / Riz", 
                    "Escalope Panée/ Haricots Verts / Patates", 
                    "Saucisses Toulouse / Lentilles", 
                    "Courgettes Farcies", 
                    "Croquettes Poisson / Riz", 
                    "Feuilletés Chèvres Epinards / Steak Pates", 
                    "Steak / Patates Sarladaise", 
                    "Jambon / Gratin De Courgettes", 
                    "Tomates Farcies / Riz", 
                    "Tatin Tomates / Côte De Porc", 
                    "Poisson Pane / Ratatouille", 
                    "Papillotes Poisson Blanc / Purée", 
                    "Fish And Chips / Frites", 
                    "Spaghettis Aux Courgettes",
                    "Boudin / Côte de porc / Purée"
                    "Tarte Chèvre épinards",
                    "Lasagne Chèvre épinards",
                    "Crêpes salées"]

menus_ete = ["Salade Composée", 
             "Salade De Riz", 
             "Salade De Pâtes", 
             "Piémontaise", 
             "Bruschetta", 
             "Salade César", 
             "Salade De Chèvre Chaud", 
             "Steaks / Poêlée Légumes", 
             "Cordons Bleus / Pates / Salade", 
             "Escalope Panée/ Haricots Verts", 
             "Panes Tomates / Riz",
             "Aiguillettes Poulet / Légumes Asiatiques", 
             "Paupiettes / Poêlée Parisienne ou Jardinière", 
             "Pilon Poulet / Petits Pois Carottes", 
             "Steaks Poivre / Kiddy Smile", 
             "Pizza", 
             "Poulet / Frites", 
             "Steaks Haches / Purée", 
             "Quiche Lorraine / Salade", 
             "Couscous", 
             "Fish And Chips",
             "Escalopes / Ratatouille", 
             "Crêpes Jambon Fromage / Pates", 
             "Poulet Fume / Haricots Plats", 
             "Saucisses Toulouse/ Poêlée Parisienne", 
             "Cuisse Poulet / Patates Sautées", 
             "Cotes Porcs / Haricots Verts", 
             "Saute De Porc A La Tomate / Riz", 
             "Croques Monsieur / Salade / Concombre Crème",
             "Escalope Panée/ Haricots Verts / Patates", 
             "Chèvres A Dorer / Salade/ Côtes De Porc / Purée Pois Cassés", 
             "Courgettes Farcies", 
             "Pave Porc Ciboulette / Patates Au Four Crème Fraiche", 
             "Croquettes Poisson / Riz", 
             "Poulet Marine/ Patates Sautées", 
             "Feuilletés Chèvres Epinards / Steak Pates", 
             "Barbecue", 
             "Pain De Poisson / Salade", 
             "Apéro Dinatoire", 
             "Jambon / Gratin De Courgettes", 
             "Tomates Farcies / Riz", 
             "Tatin Tomates / Côte De Porc", 
             "Haut De Poulet / Tomates Provençales", 
             "Poisson Pane / Ratatouille", 
             "Papillotes Poisson Blanc / Purée",
             "Spaghettis Aux Courgettes",
             "Tagliatelle de concombre saumon fumé crème fraiche",
             "Tarte Thon et Tomate",
             "Tarte Chèvre épinards",
             "Lasagne Chèvre épinards",
             "Crêpes salées"]

menus_automne = ["Poule Au Riz", 
                 "Sauté De Porc", 
                 "Steaks / Poêlée Légumes", 
                 "Palette A La Diable / Purée", 
                 "Escalope Panée / Haricots Verts", 
                 "Coquillettes Au Jambon", 
                 "Steak Hache Œuf Plat / Galette De Pommes De Terre", 
                 "Cannelloni Gratines / Salade", 
                 "Saucisses Toulouse / Carottes Sautées", 
                 "Panes Tomates / Riz", 
                 "Saumon Beurre / Riz", 
                 "Filet Mignon / Purée De Carottes", 
                 "Paupiettes / Poêlée Parisienne", 
                 "Pilon Poulet / Petits Pois Carottes", 
                 "Blanquette De Porc / Riz", 
                 "Cotes Porc / Pâtes", 
                 "Steaks Poivre / Kiddy Smile", 
                 "Tagliatelle Saumon", 
                 "Pizza", 
                 "Poulet / Frites", 
                 "Steaks Haches / Purée", 
                 "Cuisse Dinde / Petits Pois Carottes", 
                 "Raviolis", 
                 "Omelette Ciboulette / Patates Rissolées", 
                 "Hachis Parmentier", 
                 "Quiche Lorraine / Salade", 
                 "Penne / Poulet / TomatesSéchées / Mozza", 
                 "Nems / Riz Cantonnais", 
                 "Parmentier Poisson", 
                 "Lasagnes / Salade", 
                 "Couscous", 
                 "Escalopes / Ratatouille", 
                 "Spaghettis Boulettes Sauce Napo", 
                 "Crêpes Jambon Fromage / Pates", 
                 "Gratin Choux Fleurs / Jambon", 
                 "PotAuFeu", 
                 "Tarte Maroilles / Salade", 
                 "Osso Bucco", 
                 "Roti De Porc / Carottes Vichy", 
                 "Croques Monsieur / Salade Boursin", 
                 "Poulet Fume / Haricots Plats", 
                 "Gratin Dauphinois", 
                 "Steak Hache / Purée", 
                 "Saucisses Toulouse / Poêlée Parisienne", 
                 "Gratin Coquillettes / Jambon", 
                 "Risotto / Jambon Sec", 
                 "Cuisses Poulet / Petits Pois Carottes", 
                 "Moussaka",
                 "Bœuf Strogonov / Pates",
                 "Cuisse Poulet / Patates Sautées",
                 "Cotes Porcs / Haricots Verts",
                 "Saute De Porc A La Tomate / Riz",
                 "Escalope Panée / Haricots Verts / Patates",
                 "Saucisses Toulouse / Purée Pois Casses ",
                 "Saucisses Toulouse / Lentilles",
                 "Courgettes Farcies",
                 "Poisson / Riz",
                 "Feuilletés Chèvres Epinards / Steak Pates",
                 "Quiche Poireaux",
                 "Bœuf Bourguignon / Coquillettes",
                 "Jambon / Gratin De Courgettes",
                 "Tomates Farcies / Riz",
                 "Tatin Tomates / Côte De Porc",
                 "Bœuf Mijote Aux Oignons / Patates",
                 "Poisson Pane / Ratatouille",
                 "Papillotes Poisson Blanc / Purée",
                 "Saucisse Morteau / Légumes Potée",
                 "Rougaille saucisse",
                 "Boudin / Côte de porc / Purée",
                 "Tarte Chèvre épinards",
                 "Lasagne Chèvre épinards"]

menus_hiver = ["Soupe", 
                "Raclette", 
                "Fondue", 
                "Tartiflette",
                "Poule Au Riz", 
                "Sauté De Porc", 
                "Cannellonis Gratines / Salade",
                "Saucisses Toulouse / Carottes Sautées", 
                "Panes Tomates / Riz", 
                "Paupiettes / Poêlée Parisienne", 
                "Blanquette De Porc / Riz", 
                "Côtes Porc / Pâtes", 
                "Steaks Poivre / Kiddy Smile", 
                "Tagliatelles Saumon", 
                "Pizza", 
                "Poulet / Frites", 
                "Steaks Haches / Purée", 
                "Cuisse Dinde / Petits Pois Carottes", 
                "Raviolis", 
                "Hachis Parmentier", 
                "Penne/Poulet/Tomates Séchées / Mozza",
                "Nems / Riz Cantonnais",
                "Parmentier Poisson",
                "Lasagnes / Salade",
                "Couscous",
                "Escalopes / Ratatouille",
                "Spaghettis Boulettes Sauce Napo",
                "Crêpes Jambon Fromage / Pates",
                "Gratin Choux Fleurs / Jambon",
                "Pot Au Feu",
                "Tarte Maroilles / Salade",
                "Osso Bucco",
                "Roti De Porc / Carottes Vichy",
                "Gratin Dauphinois",
                "Steak Hache / Purée",
                "Gratin Coquillettes / Jambon",
                "Risotto / Jambon Sec",
                "Cuisses Poulet / Petits Pois Carottes",
                "Moussaka",
                "Pommes De Terre Suédoises Lard",
                "Cuisse Poulet / Patates Sautées",
                "Cotes Porcs / Haricots Verts",
                "Saute De Porc A La Tomate / Riz",
                "Escalope Panée/ Haricots Verts / Patates",
                "Gratin De Crozets / Crème / Parmesan / Jambon Cru",
                "Courgettes Farcies",
                "Feuilletés Chèvres Epinards / Steak Pates",
                "Bœuf Bourguignon / Coquillettes",
                "Tomates Farcies / Riz",
                "Poisson Pane / Ratatouille",
                "Papillotes Poisson Blanc / Purée",
                "Saucisse Morteau / Légumes Potée",
                "Rougaille saucisse",
                "Boudin / Côte de porc / Purée",
                "Tarte Chèvre épinards",
                "Lasagne Chèvre épinards"]